name: Build and deploy

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.menuma.online
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: menuma/menuma-dashboard

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.menuma.online/menuma/dashboard:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            NEXT_PUBLIC_BACKEND_BASEURL=${{ vars.NEXT_PUBLIC_BACKEND_BASEURL }}
            NEXT_PUBLIC_BACKEND_SOCKET_SERVER_HOST=${{ vars.NEXT_PUBLIC_BACKEND_SOCKET_SERVER_HOST }}
            NEXT_PUBLIC_BACKEND_SOCKET_SERVER_SECURE=${{ vars.NEXT_PUBLIC_BACKEND_SOCKET_SERVER_SECURE }}
            NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }}

      - name: Call API to update server
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ vars.SERVER_UPDATE_URL }}
          accept: 200
          #          headers:  '{ "Authorization": "Bearer mytoken" }'
          headers: ${{ secrets.SERVER_UPDATE_HEADER }}
          timeout: 10000
          retries: 3
